services:

  inquisitor:
    image: inquisitor
    container_name: inquisitor
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - inquisitor

  server:
    image: server
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - inquisitor
    ports:
      - "20:20"
      - "21:21"

  client:
    image: client
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - inquisitor

networks:
  inquisitor:
    driver: bridge
